language: python
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
install: pip install tox
script: python setup.py test
deploy:
  provider: pypi
  user: bozoh
  password:
    secure: U6q7kiAPMfc7MzvJIHBXbVv3wASKKetaeT89+2GKQnNdNFLDvXbJy3iYHqn0gZez7IZZfNVjlkwA8zzh1Nx79hhK6FEH0K+vHUHs59latjpzEBJ3yIytlYMFCEOw/XT2kzFYhWhSgMr5it0J+69KFL2LzAPvrKPKefvivxzKXdhU6TyMPgts+qujcaZ5mCVbtkewpsz/8ljRtpaUT3zw0uuPXGiOG+B5yCpp2xBqEdEcDHT9jWVLM9lZyGEf30bmD98wfwk7a8HxkSyKAeaH5Lfw610tWlDIovGaTQo3GXyGblTZ718p8lYZJAYgreEvM95LptByIB8zmO/YLLJdzxpjZunq5+qJxmXmUb+dEGWFZTxzd94UIrnrzXJkrvU4TBNoYaAUgy7NUcTzcSQ48tYTmi6uT+m0vYbeb3D/VmMXuJutHBchvjkkIM4d5YrJ1eUsl1ASS9YlBd5i7BCzK0/0cxGdtxtZAcsX7lktKS8RfjXQ4YpuVJnUm4+rQUq3I7+VRE9EjC8ZmI7Ow3H6kKCccgHfV9nyAMNdpKp4s8PjfACgc73x6que0d+/JZUITPzw2ANAIrVujAPuII+fCFWv0I1n3vN2+cs+fej2FRy1cW5c2KznJFN8/trDMfGdcK1drnZ2ObIZai2QQeezNWVOTyGs8VtzuU29cuoG088=
  on:
    tags: true
notifications:
  email: onchange
